# Параметры обучения
epochs: 20
batch_size: 8
learning_rate: 0.001
momentum: 0.9

# Пути к данным
train_data_path: "data/train/"
test_data_path: "data/test/"

# Размеры изображения
image_size: [224, 224]  # Размер изображений для модели

# Преобразования для данных
transforms:
  train_transforms:
    - Resize: [224, 224]
    - ToTensor: true
    - Normalize: [0.485, 0.456, 0.406]
  test_transforms:
    - Resize: [224, 224]
    - ToTensor: true
    - Normalize: [0.485, 0.456, 0.406]
